Repository softeer5th/be-was-2025, pull requests merged in 2025-02, with the labels that each got.

#101 [웹서버 7-1단계] 송민규 제출합니다.
  README.md
  build.gradle
  src/main/java/db/ArticleDatabase.java
  src/main/java/db/DataSource.java
  src/main/java/db/Database.java
  src/main/java/db/UserDatabase.java
  src/main/java/dto/Cursor.java
  src/main/java/http/HttpSession.java
  src/main/java/http/HttpSessionStorage.java
  src/main/java/http/request/HttpRequestBody.java
  src/main/java/http/response/HttpResponse.java
  src/main/java/http/servlet/ArticleServlet.java
  src/main/java/http/servlet/FrontControllerServlet.java
  src/main/java/http/servlet/HomeServlet.java
  src/main/java/http/servlet/LoginServlet.java
  src/main/java/http/servlet/MyPageServlet.java
  src/main/java/http/servlet/RegisterServlet.java
  src/main/java/model/Article.java
  src/main/java/model/User.java
  src/main/java/view/TemplateEngine.java
  src/main/java/view/View.java
  src/main/resources/application.properties
  src/main/resources/static/article/index.html
  src/main/resources/static/index.html
  src/main/resources/static/main.css
Labels: week3-1

#102 [웹서버 7-1단계] 김선오
  build.gradle
  src/main/java/DAO/ArticleDAO.java
  src/main/java/DAO/H2Connection.java
  src/main/java/DAO/SessionDAO.java
  src/main/java/DAO/UserDAO.java
  src/main/java/admin/adminDAO.java
  src/main/java/db/Database.java
  src/main/java/model/Article.java
  src/main/java/model/ContentType.java
  src/main/java/model/Cookie.java
  src/main/java/model/Session.java
  src/main/java/model/User.java
  src/main/java/webserver/HTTPExceptions.java
  src/main/java/webserver/RequestHandler.java
  src/main/java/webserver/ResponseHandler.java
  src/main/java/webserver/WebServer.java
  src/main/java/webserver/request/HTTPRequestBody.java
  src/main/java/webserver/request/HTTPRequestHeader.java
  src/main/java/webserver/request/RequestHandler.java
  src/main/java/webserver/request/RequestProcessor.java
  src/main/java/webserver/request/api/LatestArticleApiHandler.java
  src/main/java/webserver/request/api/LoginStatusApiHandler.java
  src/main/java/webserver/request/api/NextArticleApiHandler.java
  src/main/java/webserver/request/api/PreviousArticleApiHandler.java
  src/main/java/webserver/request/route/DefaultPageHandler.java
  src/main/java/webserver/request/route/LoginPageHandler.java
  src/main/java/webserver/request/route/MyPageHandler.java
  src/main/java/webserver/request/route/RegistrationPageHandler.java
  src/main/java/webserver/request/route/WritePageHandler.java
  src/main/java/webserver/request/service/UserCreateHandler.java
  src/main/java/webserver/request/service/UserLoginHandler.java
  src/main/java/webserver/request/service/UserLogoutHandler.java
  src/main/java/webserver/request/service/UserWriteHandler.java
  src/main/java/webserver/request/staticResource/StaticResourceHandler.java
  src/main/java/webserver/response/HTTPResponse.java
  src/main/java/webserver/response/HTTPResponseBody.java
  src/main/java/webserver/response/HTTPResponseHeader.java
  src/main/java/webserver/response/ResponseHandler.java
  src/main/resources/static/article/index.html
  src/main/resources/static/article/write.html
  src/main/resources/static/global.css
  src/main/resources/static/index.html
  src/main/resources/static/mypage/index.html
  src/test/java/webserver/HTTPRequestHeaderTest.java
  src/test/java/webserver/RequestHandlerTest.java
Labels: week3-1

#103 [웹서버 7-1단계] 전경석 제출합니다.
  README.md
  build.gradle
  src/main/java/db/Database.java
  src/main/java/handler/GetHandler.java
  src/main/java/handler/PostHandler.java
  src/main/java/http/HttpRequest.java
  src/main/java/http/HttpResponse.java
  src/main/java/model/Comment.java
  src/main/java/model/Post.java
  src/main/java/model/User.java
  src/main/java/util/SessionUtil.java
  src/main/java/webserver/RequestHandler.java
  src/main/java/webserver/RequestRouter.java
  src/main/resources/static/article/index.html
  src/main/resources/static/comment/index.html
  src/main/resources/static/global.css
  src/main/resources/static/index.html
  src/main/resources/static/login/index.html
  src/main/resources/static/mypage/index.html
  src/main/resources/static/mypage/update_failed.html
  src/main/resources/static/registration/index.html
  src/main/resources/static/registration/registration_failed.html
Labels: week3-1

#105 [웹 서버 7-1] 송지웅 제출합니다.
  build.gradle
  src/main/java/db/Database.java
  src/main/java/db/Tables.java
  src/main/java/db/connection/ConnectionProvider.java
  src/main/java/db/connection/RealConnectionProvider.java
  src/main/java/db/connection/TestConnectionProvider.java
  src/main/java/entrypoint/UserEntryPoint.java
  src/main/java/model/Post.java
  src/main/java/webserver/enumeration/HTTPContentType.java
  src/main/java/webserver/enumeration/HTTPStatusCode.java
  src/main/java/webserver/functional/TypeParser.java
  src/main/java/webserver/functional/TypeParserFactory.java
  src/main/java/webserver/message/body/BodyParserFactory.java
  src/main/java/webserver/message/body/BodyPrinter.java
  src/main/java/webserver/message/body/MultipartParser.java
  src/main/java/webserver/message/record/FileRecord.java
  src/main/java/webserver/reader/StaticFileReader.java
  src/main/java/webserver/resolver/ExceptionResolver.java
  src/main/java/webserver/resolver/RequestMethodWrapper.java
  src/main/java/webserver/resolver/SequentialResolver.java
  src/main/java/webserver/resolver/StaticResourceResolver.java
  src/main/java/webserver/resolver/factory/MethodResolverFactory.java
  src/main/java/webserver/resolver/factory/ResolverFactory.java
  src/main/java/webserver/resolver/records/ParameterMetaInfo.java
  src/main/java/webserver/writer/html/HTMLElement.java
  src/main/java/webserver/writer/html/HTMLTag.java
  src/main/java/webserver/writer/html/template/ErrorPageWriter.java
  src/main/java/webserver/writer/html/template/IndexPageWriter.java
  src/main/resources/static/article/index.html
  src/main/resources/static/global.css
  src/main/resources/static/index.html
  src/main/resources/static/main.css
  src/test/java/UserTest.java
Labels: week3-1

#110 [웹 서버 7-1 단계] 김유리
  .gitignore
  .idea/.gitignore
  .idea/.name
  .idea/compiler.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/vcs.xml
  build.gradle
  src/main/java/config/AppConfig.java
  src/main/java/db/ArticleDataManger.java
  src/main/java/db/Database.java
  src/main/java/db/JdbcArticleDataManager.java
  src/main/java/db/JdbcSessionDataManager.java
  src/main/java/db/JdbcUserDataManager.java
  src/main/java/db/LocalSessionDataManager.java
  src/main/java/db/LocalUserDataManager.java
  src/main/java/db/SessionDataManager.java
  src/main/java/db/UserDataManager.java
  src/main/java/exception/DBErrorCode.java
  src/main/java/exception/SessionErrorCode.java
  src/main/java/exception/UserErrorCode.java
  src/main/java/handler/ArticleCreateHandler.java
  src/main/java/handler/FileRequestHandler.java
  src/main/java/handler/UserLoginHandler.java
  src/main/java/handler/UserLogoutHandler.java
  src/main/java/handler/UserRegisterHandler.java
  src/main/java/http/HttpRequestInfo.java
  src/main/java/http/HttpStatus.java
  src/main/java/model/Article.java
  src/main/java/model/User.java
  src/main/java/router/RequestRouter.java
  src/main/java/util/JdbcUtil.java
  src/main/java/webserver/RequestHandler.java
  src/main/resources/static/article/index.html
  src/main/resources/static/comment/index.html
  src/main/resources/static/global.css
  src/main/resources/static/index.html
  src/main/resources/static/main/index.html
  src/test/java/handler/FileRequestHandlerTest.java
  src/test/java/handler/UserLoginHandlerTest.java
  src/test/java/handler/UserLogoutHandlerTest.java
  src/test/java/handler/UserRegisterHandlerTest.java
Labels: week3-1

#108 [웹 서버 7단계] 천성필 제출합니다.
  .gitignore
  build.gradle
  src/main/java/db/Database.java
  src/main/java/http/handler/PostHandler.java
  src/main/java/http/handler/StaticResourceHandler.java
  src/main/java/http/handler/UserHandler.java
  src/main/java/http/request/HttpRequest.java
  src/main/java/http/request/HttpRequestParser.java
  src/main/java/http/response/DynamicHtmlBuilder.java
  src/main/java/http/response/HttpResponse.java
  src/main/java/http/router/Router.java
  src/main/java/model/Article.java
  src/main/java/model/Comment.java
  src/main/java/util/HttpRequestUtil.java
  src/main/java/webserver/WebServer.java
  src/main/resources/static/article/index.html
  src/main/resources/static/comment/index.html
  src/main/resources/static/index.html
  src/test/java/http/handler/UserHandlerTest.java
Labels: week3-1, week3-2

#111 [웹 서버 7단계] 김현원 제출합니다
  build.gradle
  src/main/java/db/ArticleDao.java
  src/main/java/db/ArticleInitializer.java
  src/main/java/db/Database.java
  src/main/java/db/UserDao.java
  src/main/java/db/UserInitializer.java
  src/main/java/db/transaction/Transaction.java
  src/main/java/db/transaction/TransactionManager.java
  src/main/java/db/transaction/TransactionTemplate.java
  src/main/java/exception/ArticleException.java
  src/main/java/exception/ErrorCode.java
  src/main/java/handler/dynamic_handler/DynamicHtmlHandler.java
  src/main/java/handler/dynamic_handler/HomeDynamicHtmlHandler.java
  src/main/java/handler/dynamic_handler/MyPageDynamicHtmlHandler.java
  src/main/java/handler/mapping/DynamicHtmlHandlerMapping.java
  src/main/java/handler/mapping/RequestHandlerMapping.java
  src/main/java/handler/request/ArticleCreateRequestHandler.java
  src/main/java/handler/request/FileRequestHandler.java
  src/main/java/handler/request/ProfileImageSaveRequestHandler.java
  src/main/java/handler/request/RequestHandler.java
  src/main/java/handler/request/SingleArticleRequestHandler.java
  src/main/java/handler/request/UserLoginRequestHandler.java
  src/main/java/handler/request/UserLogoutRequestHandler.java
  src/main/java/handler/request/UserSignUpRequestHandler.java
  src/main/java/handler/request_handler/FileRequestHandler.java
  src/main/java/handler/request_handler/UserSignUpRequestHandler.java
  src/main/java/http/enums/HttpStatus.java
  src/main/java/http/request/HttpHeader.java
  src/main/java/http/request/HttpRequest.java
  src/main/java/http/request/HttpRequestResolver.java
  src/main/java/http/request/MultipartPart.java
  src/main/java/http/session/SessionManager.java
  src/main/java/manager/ArticleManager.java
  src/main/java/manager/UserManager.java
  src/main/java/model/Article.java
  src/main/java/model/User.java
  src/main/java/provider/DynamicDataProvider.java
  src/main/java/provider/HomeDataProvider.java
  src/main/java/provider/Model.java
  src/main/java/provider/MyPageDataProvider.java
  src/main/java/template/TemplateEngine.java
  src/main/java/util/DBUtil.java
  src/main/java/webserver/WebServer.java
  src/main/java/webserver/WebServlet.java
  src/main/resources/static/global.css
  src/main/resources/static/index.html
  src/main/resources/static/login/index.html
  src/main/resources/static/mypage/index.html
  src/main/resources/static/registration/index.html
  src/main/resources/static/write/index.html
  src/test/java/user/SignUpTest.java
Labels: week3-1, week3-2

#107 [웹서버 7-2단계] 박명규
  src/main/java/db/DatabaseInitializer.java
  src/main/java/db/Transaction.java
  src/main/java/db/TransactionFactory.java
  src/main/java/db/TransactionalDao.java
  src/main/java/domain/Article.java
  src/main/java/domain/ArticleDao.java
  src/main/java/domain/Comment.java
  src/main/java/domain/CommentDao.java
  src/main/java/domain/User.java
  src/main/java/domain/UserDao.java
  src/main/java/handler/IndexPageHandler.java
  src/main/java/handler/LoginHandler.java
  src/main/java/handler/MypageHandler.java
  src/main/java/handler/ReadArticleHandler.java
  src/main/java/handler/RegistrationHandler.java
  src/main/java/handler/WriteArticleHandler.java
  src/main/java/handler/WriteCommentHandler.java
  src/main/java/util/CommonUtil.java
  src/main/java/util/ExceptionUtil.java
  src/main/java/util/FileUtil.java
  src/main/java/util/HtmlEscapeUtil.java
  src/main/java/util/ReflectionUtil.java
  src/main/java/webserver/FrontController.java
  src/main/java/webserver/WebServer.java
  src/main/java/webserver/config/ServerConfig.java
  src/main/java/webserver/enums/ContentType.java
  src/main/java/webserver/enums/HttpHeader.java
  src/main/java/webserver/enums/ParsingConstant.java
  src/main/java/webserver/exception/filter/ExceptionFilterChain.java
  src/main/java/webserver/exception/filter/HttpExceptionFilter.java
  src/main/java/webserver/file/StaticResourceManager.java
  src/main/java/webserver/handler/HttpHandler.java
  src/main/java/webserver/handler/ServeStaticFileHandler.java
  src/main/java/webserver/interceptor/InterceptorChain.java
  src/main/java/webserver/request/FileUploader.java
  src/main/java/webserver/request/HttpRequest.java
  src/main/java/webserver/request/Multipart.java
  src/main/java/webserver/request/RequestBody.java
  src/main/java/webserver/response/body/FileBody.java
  src/main/java/webserver/view/renderer/IfTagRenderer.java
  src/main/java/webserver/view/renderer/TextTagRenderer.java
  src/main/resources/server-config.properties
  src/main/resources/static/global.css
  src/main/resources/static/img/addPicture.svg
  src/main/resources/static/main.css
  src/main/resources/template/article/index.html
  src/main/resources/template/comment/index.html
  src/main/resources/template/common/header.html
  src/main/resources/template/index.html
  src/main/resources/template/login/index.html
  src/main/resources/template/mypage/index.html
  src/main/resources/template/noArticle.html
  src/main/resources/template/registration/index.html
  src/test/java/handler/IndexPageHandlerTest.java
  src/test/java/handler/LoginHandlerTest.java
  src/test/java/webserver/enums/ContentTypeTest.java
Labels: week3-2
